### ISSUE TITLE
Download contained Bitrep.A Trojan? False positive?

### ISSUE THREAD

**Issue by Aylon1** [qtumproject/qtum#384] opened 2017-10-12 20:53 UTC
This issue tracker is only for technical issues related to Qtum.

### Describe the issue
Downloaded release from this site -> qtum-0.14.3-win64-setup-unsigned.exe

### Expected behaviour
No catch from Windows Defender or other virus scanner.

### Actual behaviour
![image](https://user-images.githubusercontent.com/13525135/31518588-0c62943c-afa0-11e7-9d43-dd9139a5c8ba.png)

### What version of Qtum are you using?
as above

### Machine specs:
- OS: win 10 pro
- CPU: 
- RAM: 
- Disk size:

**Comment by Earlz** [comment] 2017-10-17 20:44
This is a false positive. 

duplicate of #377

**Closed by Earlz** 2017-10-17 20:44 UTC
