### ISSUE TITLE
too many tiny utxos inhibit sending coins when fee policy is too low

### ISSUE THREAD

**Issue by smisel** [qtumproject/qtum#772] opened 2019-09-27 08:33 UTC
Testnet where fee policy is fixed receiving error transaction too high for fee policy

expected to be able to send coins. A method to prioritize utxos or delete tiny utxos which inhibit spending

Transaction too high for fee policy error when wallet has been spammed with thousands of 0.001 utxos

Send wallet many small amounts until wallet receiver can not send coins

latest

linux/windows

all versions

this is on a separate testnet where the fee has been fixed to very low. Looking for method to discard these tiny utxos as this can be used as an attack on a user to inhibit wallet. client becomes very slow with too many utxos and cannot use coin control features since the client freezes. Looking for cli method to select largest utxos to transfer funds to new wallet or method to completely remove several hundred thousand thousand 0.001 sized utxos.

**Comment by JB395** [comment] 2019-10-09 08:46
Please take a look at the `lockunspent` command. 

Perhaps you can use `listunspent` results data with grep and/or a spreadsheet to assemble the `lockunspent` commands for batches of these small UTXOs. Note that the locked UTXOs are stored in memory, and will not remain if you restart the wallet, so save them in a text file. 

(I haven’t tried this myself for many small UTXOs)

**Comment by brianrubenstein** [comment] 2019-10-09 09:52
thank you so much!

**Comment by smisel** [comment] 2019-10-09 14:24
Awesome! Trying it out now..

**Comment by JB395** [comment] 2019-10-31 21:58
Able to reproduce the "Transaction too large for fee policy" bug: on Testnet, send 3,000 0.001 UTXOs to a wallet. Without coin control, if sending ~ 0.5 QTUM (500 inputs) get "Transaction too large" error, followed by "Transaction creation failed!". If sending ~0.8 QTUM (800 UTXOs) get "Transaction too large for fee policy" followed by "Transaction creation failed". Sending amounts below those worked okay.

**Comment by Earlz** [comment] 2020-12-14 18:44
Closing as this seems to be answered

**Closed by Earlz** 2020-12-14 18:44 UTC
