### ISSUE TITLE
rpc interface  getrawtransaction  cannot get transaction info by transactionHash 

### ISSUE THREAD

**Issue by liuxiaohao** [qtumproject/qtum#639] opened 2018-12-25 06:19 UTC
I try get the transaction info use rpc cal getrawtransaction it return null  but i can get other transaction's info that in same block. 

For example I can not  get tx 54c9f889983daff449a5e51cec9c7278e2eeb4ed86dd4bec02a8c974019bb44c
but  i can get tx d34a9373b08998a24de111f5101b5c87584b02fa5c3362e2dfcd4c2999bd1487 .

**Comment by JB395** [comment] 2018-12-28 15:38
Could not reproduce.

getrawtransaction help says:

> NOTE: By default this function only works for mempool transactions. If the -txindex option is enabled, it also works for blockchain transactions. If the block which contains the transaction is known, its hash can be provided even for nodes without -txindex. Note that if a blockhash is provided, only that block will be searched and if the transaction is in the mempool or other blocks, or if this node does not have the given block available, the transaction will not be found.
> DEPRECATED: for now, it also works for transactions with unspent outputs.
> 

Without the node running the –txindex option, finding the transactions will be inconsistent. For a node running with the -txindex option, getrawtransaction (verbose) returns:

```
getrawtransaction "d34a9373b08998a24de111f5101b5c87584b02fa5c3362e2dfcd4c2999bd1487" true

{
  "txid": "d34a9373b08998a24de111f5101b5c87584b02fa5c3362e2dfcd4c2999bd1487",
  "hash": "d34a9373b08998a24de111f5101b5c87584b02fa5c3362e2dfcd4c2999bd1487",
  "version": 2,
  "size": 3766,
  "vsize": 3766,
  "locktime": 287448,
  "vin": [
    {
      "txid": "dedf92ee36964ecb5d4687298375a8fd4f8c2c6693f5312de2f2343993185e2a",
      "vout": 0,
      "scriptSig": {
        "asm": "3045022100f961972f58be3c56f06f087ace0fb61d5d962099b0aeebd47ced35230148808402204b2a2dc1cfa29a7841f8c8297336634b2c2fcb0c54a3b21bbc549add56da4d5b[ALL] 029e17fafffc1e6a4213f9c83d57231f2bb233382be6b423e74eca387eafa1c99a",
        "hex": "483045022100f961972f58be3c56f06f087ace0fb61d5d962099b0aeebd47ced35230148808402204b2a2dc1cfa29a7841f8c8297336634b2c2fcb0c54a3b21bbc549add56da4d5b0121029e17fafffc1e6a4213f9c83d57231f2bb233382be6b423e74eca387eafa1c99a"
      },
      "sequence": 4294967294
    },

<snip>

```

Without running –txindex, using getrawtransaction with the TX ID and block hash returned the transaction:

```
getrawtransaction "d34a9373b08998a24de111f5101b5c87584b02fa5c3362e2dfcd4c2999bd1487" true  "2f12c98a769a871bfc03047329ba64c3bc180140647b75ddbb7811ce56ea706d"

{
  "in_active_chain": true,
  "txid": "d34a9373b08998a24de111f5101b5c87584b02fa5c3362e2dfcd4c2999bd1487",
  "hash": "d34a9373b08998a24de111f5101b5c87584b02fa5c3362e2dfcd4c2999bd1487",
  "version": 2,
  "size": 3766,
  "vsize": 3766,
  "locktime": 287448,
  "vin": [
    {
      "txid": "dedf92ee36964ecb5d4687298375a8fd4f8c2c6693f5312de2f2343993185e2a",
      "vout": 0,
<snip>


```
Depending on your application, you could also consider the Insight API: `https://explorer.qtum.org/insight-api/tx/d34a9373b08998a24de111f5101b5c87584b02fa5c3362e2dfcd4c2999bd1487`

If you resync the blockchain starting up your node with the –txindex command line option, can you find this transaction?

**Closed** 2019-01-29 21:07 UTC
