### ISSUE TITLE
Failed test while make check

### ISSUE THREAD

**Issue by shubhamy** [qtumproject/qtum#206] opened 2017-06-28 10:02 UTC
### Describe the issue
When I run make check, 1 test failed. I ignored the error and started the qt-wallet, it got stuck at "connecting to peers" and never found any peer.

#### If so, please list the steps to reproduce below:
1. make -j2
2. make check

### Machine specs:
- OS: Ubuntu
- CPU: i5
- RAM: 8 GB
- Disk size: 500 GB

### Error Log:
test/qtumtests/condensingtransaction_tests.cpp(197): error in "condensingtransactionbehavior_tests": check tx.vin.size() == sizeVin failed
test/qtumtests/condensingtransaction_tests.cpp(198): error in "condensingtransactionbehavior_tests": check tx.vout.size() == sizeVout failed
unknown location(0): fatal error in "condensingtransactionbehavior_tests": signal: SIGSEGV, si_code: 0 (memory access violation at address: 0x00000080)
test/qtumtests/condensingtransaction_tests.cpp(200): last checkpoint

*** 895 failures detected in test suite "Bitcoin Test Suite"
test_qtum: /usr/include/boost/thread/pthread/condition_variable_fwd.hpp:81: boost::condition_variable::~condition_variable(): Assertion `!ret' failed.
FAIL test/test_qtum (exit status: 134)

**Comment by Earlz** [comment] 2017-06-28 12:21
This will be fixed soon, it was caused by a last minute consensus bug fix in commit b5402482bf311c5d3842f069d44028a417d437b5

**Comment by Earlz** [comment] 2017-06-28 22:07
Fixed in #211

**Closed by Earlz** 2017-06-28 22:07 UTC
